version: '2.1'

volumes:
    db-mongo:
    backend-rest:
    news-scraper-workers-go:

networks:
    my-network:
        external: true

services:
    db-mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        hostname:
            "db-mongo"
        networks:
            -  my-network
        command: ["--bind_ip_all"]
        expose: 
            - "27017"
    backend-rest:
        image: backend-rest
        ports:
            - "8002:8002"
        restart: always
        env_file:
            - .env
        networks:
            -  my-network
    news-scraper-workers-go:
        image: news-scraper-workers-go
        restart: always
        env_file:
            - .env
        networks:
            -  my-network